### ISSUE TITLE
WiiU Pro controller support

### ISSUE THREAD

**Issue by niknice** [Oibaf66/fbzx-wii#57]
https://gbatemp.net/threads/libwupc-a-wiiu-pro-controller-library-for-wii-homebrew-applications.371574/
Is this possible?? Many thanks

**Comment by Oibaf66** [comment]
I have opened a thread here to test the Wii U Pro controller support

https://gbatemp.net/threads/fbzx-wii-wii-u-pro-controller-support.455944/

**Comment by Oibaf66** [comment]
In version 15 the Wii U Pro controller support was added
